version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./docker/psql:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.development
    working_dir: /api
    volumes:
      - .:/api
    command: "npm start"

  tests:
    build: .
    volumes:
      - .:/api
    working_dir: /api
    env_file:
      - .env
      - .env.test
    links:
      - db
    stop_signal: SIGKILL
    command: "tail -F /dev/null"

volumes: 
  db:
