version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data

  db_test:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    depends_on:
      - db
      - db_test
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.dev
      - .env.test
    working_dir: /api
    volumes:
      - .:/api
    command: "npm start"

volumes: 
  db:
