version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/mysql

  web:
    depends_on:
      - db
    build: ./
    ports:
      - 3000:3000
    environment:
      - .env
    working_dir: /api
    volumes:
      - .:/api
    command: "npm start"

volumes: 
  db:
