version: '3.8'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - fidecloud
    volumes:
      - api-db:/var/lib/postgresql/gui

  api-db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - fidecloud

  web:
    depends_on:
      - api-db
    build: ./
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    working_dir: /api
    volumes:
      - .:/api
    command: "npm run start:dev"
    networks:
      - fidecloud

volumes:
  api-db:

networks:
  fidecloud:
    driver: bridge
